### ISSUE TITLE
R CMD check --as-cran

### ISSUE THREAD

**Issue by edzer** [Open-EO/openeo-r-client#84]
Gives the following messages, which all need to be addressed; the URLs need to be replaced with the ones following "moved to")
```
Non-FOSS package license (file LICENSE)

Package has a VignetteBuilder field but no prebuilt vignette index.

Found the following (possibly) invalid URLs:
  URL: 
    From: README.md
    Message: Empty URL
  URL: http://openeo.org/ (moved to https://openeo.org/)
    From: README.md
    Status: 200
    Message: OK
  URL: https://open-eo.github.io/openeo-api/ (moved to https://api.openeo.org/)
    From: README.md
    Status: 200
    Message: OK
  URL: https://open-eo.github.io/openeo-api/apireference/#tag/Capabilities/paths/~1.well-known~1openeo/get (moved to https://api.openeo.org/apireference/)
    From: man/api_versions.Rd
    Status: 404
    Message: Not Found
  URL: https://open-eo.github.io/openeo-api/processes/#callbacks (moved to https://api.openeo.org/processes/)
    From: man/CallbackArgument.Rd
          man/CallbackValue.Rd
    Status: 404
    Message: Not Found
  URL: https://open-eo.github.io/openeo-api/processes/#openeo-specific-formats (moved to https://api.openeo.org/processes/)
    From: man/Parameter.Rd
    Status: 404
    Message: Not Found
  URL: https://open-eo.github.io/openeo-api/v/0.0.1/ (moved to https://api.openeo.org/v/0.0.1/)
    From: README.md
    Status: 404
    Message: Not Found
  URL: https://open-eo.github.io/openeo-api/v/0.0.2/ (moved to https://api.openeo.org/v/0.0.2/)
    From: README.md
    Status: 404
    Message: Not Found
  URL: https://open-eo.github.io/openeo-api/v/0.3.1/ (moved to https://api.openeo.org/v/0.3.1/)
    From: README.md
    Status: 200
    Message: OK
  URL: https://open-eo.github.io/openeo-api/v/0.4.2/ (moved to https://api.openeo.org/v/0.4.2/)
    From: README.md
    Status: 200
    Message: OK
  URL: https://open-eo.github.io/openeo-api/v/0.4.2/processgraphs/#callbacks (moved to https://api.openeo.org/v/0.4.2/processgraphs/)
    From: man/CallbackArgument.Rd
          man/CallbackValue.Rd
    Status: 200
    Message: OK

The Title field starts with the package name.
The Title field should be in title case. Current version is:
‘openEO client interface’
In title case that is:
‘openEO Client Interface’
```
